name: server test

on:
  push:
    branches: [deus/test-server]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: root-npm-cache
        with:
          path: 'node_modules'
          key: root-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: server-npm-cache
        with:
          path: 'server/node_modules'
          key: server-npm-${{ hashFiles('server/package-lock.json') }}
      - run: npm install & npm install --prefix server & wait
        if: steps.root-npm-cache.outputs.cache-hit != 'true' || steps.server-npm-cache.outputs.cache-hit != 'true'
      - run: |
          if [ -f "server/deps.txt" ]; then
            npm install $(cat server/deps.txt)
            unlink server/deps.txt
          fi
      - name: lint
        run: npm run lint:fix:server
      - run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "Formatted"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD
          fi
      - name: generate
        run: npm run generate:server
      - name: typecheck
        run: npm run typecheck:server
      - run: |
          cp client/.env.example client/.env
          cp server/.env.example server/.env
          cp docker/dev/.env.example docker/dev/.env
          docker compose up -d
      - name: migrate
        run: npm run migrate:dev:createonly --prefix server -- --name deus
      - run: |
          git add -N server/prisma/migrations
          if git diff --quiet --exit-code; then
            echo "No changes to commit"
          else
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add server/prisma/migrations
            git commit -m "Created migration"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD
          fi
      - name: test
        run: npm run test:server
      - name: build
        run: npm run build --prefix server
